/* eslint-disable no-unused-vars */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/models/MixedScenarios.glb 
*/

import React, { useCallback, useEffect, useRef, useState } from "react";
import * as THREE from "three";
import { useFrame, useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";
import { useControls } from "./UseControls";
import { RigidBody, useRapier } from "@react-three/rapier";

export function MixedScenes(props) {
  const group = React.useRef();
  //  const { scene } = useGLTF("/MixedScenarios.glb");
  //  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  //const { actions } = useAnimations(animations, group);
  const { nodes, materials, animations } = useGLTF(
    "./models/MixedScenarios.glb"
  );
  const controls = useControls();
  const spaceshipRef = useRef();
  const fixedColliderRef = useRef();
  const cameraTarget = useRef();
  const cameraPosition = useRef();
  const cameraWorldPosition = useRef(new THREE.Vector3());
  const cameraLookAtWorldPosition = useRef(new THREE.Vector3());
  const cameraLookAt = useRef(new THREE.Vector3());

  const [initialPosition] = useState(new THREE.Vector3(-0.163, 0.566, -0.056));
  const [initialRotation] = useState(
    new THREE.Quaternion().setFromEuler(new THREE.Euler(0, 0, 0))
  );

  const resetGame = useCallback(() => {
    const spaceship = spaceshipRef.current;
    if (spaceship) {
      spaceship.setTranslation(initialPosition, true);
      spaceship.setRotation(initialRotation, true);
      spaceship.setLinvel({ x: 0, y: 0, z: 0 }, true);
      spaceship.setAngvel({ x: 0, y: 0, z: 0 }, true);
    }
  }, [initialPosition, initialRotation]);

  useEffect(() => {
    const handleKeyDown = (event) => {
      if (event.key === "r" || event.key === "R") {
        resetGame();
      }
    };

    window.addEventListener("keydown", handleKeyDown);
    return () => {
      window.removeEventListener("keydown", handleKeyDown);
    };
  }, [resetGame]);

  useFrame(({ camera }) => {
    cameraPosition.current.getWorldPosition(cameraWorldPosition.current);
    camera.position.lerp(cameraWorldPosition.current, 1);

    if (cameraTarget.current) {
      cameraTarget.current.getWorldPosition(cameraLookAtWorldPosition.current);
      cameraLookAt.current.lerp(cameraLookAtWorldPosition.current, 1);

      camera.lookAt(cameraLookAt.current);
    }

    const spaceship = spaceshipRef.current;

    if (!spaceship) return;

    const impulse = 5;
    const torque = 0.7;
    const maxSpeed = 15;
    const velocity = spaceship.linvel();
    const speed = Math.sqrt(
      velocity.x ** 2 + velocity.y ** 2 + velocity.z ** 1.5
    );

    if (speed > maxSpeed) {
      const scale = maxSpeed / speed;
      spaceship.setLinvel(
        {
          x: velocity.x * scale,
          y: velocity.y * scale,
          z: velocity.z * scale,
        },
        true
      );
    }

    const forwardVector = new THREE.Vector3(0, 0, 4).applyQuaternion(
      spaceship.rotation()
    );

    if (controls.forward) {
      spaceship.applyImpulse(forwardVector.multiplyScalar(impulse));
    }
    if (controls.back) {
      spaceship.applyImpulse({ x: 0, y: -4, z: 0 });
    }
    if (controls.down) {
      spaceship.applyImpulse(forwardVector.multiplyScalar(-impulse));
    }
    if (controls.left) {
      spaceship.applyTorqueImpulse({ x: 0, y: torque, z: 0 });
    }
    if (controls.right) {
      spaceship.applyTorqueImpulse({ x: 0, y: -torque, z: 0 });
    }
    if (controls.jump) {
      spaceship.applyImpulse({ x: 0, y: 1, z: 0 });
    }
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="Armature_druide"
          position={[22.495, 0.878, 6.829]}
          rotation={[Math.PI, -0.978, Math.PI]}
          scale={68.914}
        >
          <primitive object={nodes.root} />
          <group name="druid">
            <skinnedMesh
              name="druid001"
              geometry={nodes.druid001.geometry}
              material={materials.color_main}
              skeleton={nodes.druid001.skeleton}
            />
            <skinnedMesh
              name="druid001_1"
              geometry={nodes.druid001_1.geometry}
              material={materials["Material.006"]}
              skeleton={nodes.druid001_1.skeleton}
            />
          </group>
        </group>
        <group
          name="tmpParent018"
          position={[-69.023, 27.892, 174.533]}
          rotation={[0, 0.473, 0]}
          scale={1.719}
        >
          <group name="race">
            <group name="body005" scale={6.282}>
              <mesh
                name="Mesh_body014"
                geometry={nodes.Mesh_body014.geometry}
                material={materials.paintRed}
              />
              <mesh
                name="Mesh_body014_1"
                geometry={nodes.Mesh_body014_1.geometry}
                material={materials.plastic}
              />
              <mesh
                name="Mesh_body014_2"
                geometry={nodes.Mesh_body014_2.geometry}
                material={materials.window}
              />
              <mesh
                name="Mesh_body014_3"
                geometry={nodes.Mesh_body014_3.geometry}
                material={materials._defaultMat}
              />
            </group>
            <group name="wheel_backLeft005" scale={6.282}>
              <mesh
                name="Mesh_wheel_frontLeft028"
                geometry={nodes.Mesh_wheel_frontLeft028.geometry}
                material={materials["carTire.014"]}
              />
              <mesh
                name="Mesh_wheel_frontLeft028_1"
                geometry={nodes.Mesh_wheel_frontLeft028_1.geometry}
                material={materials["plastic.015"]}
              />
              <mesh
                name="Mesh_wheel_frontLeft028_2"
                geometry={nodes.Mesh_wheel_frontLeft028_2.geometry}
                material={materials.paintYellow}
              />
            </group>
            <group name="wheel_backRight005" scale={6.282}>
              <mesh
                name="Mesh_wheel_frontLeft029"
                geometry={nodes.Mesh_wheel_frontLeft029.geometry}
                material={materials["carTire.014"]}
              />
              <mesh
                name="Mesh_wheel_frontLeft029_1"
                geometry={nodes.Mesh_wheel_frontLeft029_1.geometry}
                material={materials["plastic.015"]}
              />
              <mesh
                name="Mesh_wheel_frontLeft029_2"
                geometry={nodes.Mesh_wheel_frontLeft029_2.geometry}
                material={materials.paintYellow}
              />
            </group>
            <group name="wheel_frontLeft005" scale={6.282}>
              <mesh
                name="Mesh_wheel_frontLeft030"
                geometry={nodes.Mesh_wheel_frontLeft030.geometry}
                material={materials["carTire.014"]}
              />
              <mesh
                name="Mesh_wheel_frontLeft030_1"
                geometry={nodes.Mesh_wheel_frontLeft030_1.geometry}
                material={materials["plastic.015"]}
              />
              <mesh
                name="Mesh_wheel_frontLeft030_2"
                geometry={nodes.Mesh_wheel_frontLeft030_2.geometry}
                material={materials.paintYellow}
              />
            </group>
            <group name="wheel_frontRight005" scale={6.282}>
              <mesh
                name="Mesh_wheel_frontLeft011"
                geometry={nodes.Mesh_wheel_frontLeft011.geometry}
                material={materials["carTire.014"]}
              />
              <mesh
                name="Mesh_wheel_frontLeft011_1"
                geometry={nodes.Mesh_wheel_frontLeft011_1.geometry}
                material={materials["plastic.015"]}
              />
              <mesh
                name="Mesh_wheel_frontLeft011_2"
                geometry={nodes.Mesh_wheel_frontLeft011_2.geometry}
                material={materials.paintYellow}
              />
            </group>
          </group>
        </group>
        <group name="palm_short" position={[-0.494, 0, 228.866]} scale={13.507}>
          <mesh
            name="Group_23"
            geometry={nodes.Group_23.geometry}
            material={materials["wood.001"]}
            position={[-0.665, 0, 0.607]}
            scale={[0.79, 0.6, 0.79]}
          />
          <mesh
            name="Group_25"
            geometry={nodes.Group_25.geometry}
            material={materials["leaves.001"]}
            position={[0, 1.327, 0]}
            scale={0.573}
          />
        </group>
        <mesh
          name="boat_large_8angles"
          geometry={nodes.boat_large_8angles.geometry}
          material={materials.wood}
          position={[51.714, 5.505, -128.684]}
          rotation={[0.598, 0.246, 0.646]}
          scale={19.05}
        />
        <group
          name="cannonLarge"
          position={[-63.417, 2.967, -40.543]}
          rotation={[0.019, -0.367, 0.048]}
          scale={29.594}
        >
          <mesh
            name="cannonLarge_1"
            geometry={nodes.cannonLarge_1.geometry}
            material={materials["wood.005"]}
          />
          <mesh
            name="cannonLarge_2"
            geometry={nodes.cannonLarge_2.geometry}
            material={materials["iron.002"]}
          />
          <mesh
            name="barrel_1"
            geometry={nodes.barrel_1.geometry}
            material={materials["iron.002"]}
            position={[0, 0.348, -0.067]}
            rotation={[0.559, 0.069, -0.146]}
          />
        </group>
        <mesh
          name="Barn_001"
          geometry={nodes.Barn_001.geometry}
          material={materials.None}
          position={[-66.995, 6.987, -91.536]}
          rotation={[-Math.PI, 1.381, -Math.PI]}
          scale={10.024}
        />
        <group
          name="axeDouble_uncommon"
          position={[-19.869, 23.339, -57.478]}
          rotation={[1.171, 0.828, -2.734]}
          scale={17.792}
        >
          <mesh
            name="Cube014"
            geometry={nodes.Cube014.geometry}
            material={materials["Metal.074"]}
          />
          <mesh
            name="Cube014_1"
            geometry={nodes.Cube014_1.geometry}
            material={materials["BrownDark.039"]}
          />
          <mesh
            name="Cube014_2"
            geometry={nodes.Cube014_2.geometry}
            material={materials["Stone.012"]}
          />
        </group>
        <group
          name="axe_uncommon"
          position={[64.188, 52.022, -127.32]}
          rotation={[-1.676, 0.908, 2.662]}
          scale={32.598}
        >
          <mesh
            name="Cube017"
            geometry={nodes.Cube017.geometry}
            material={materials["Metal.072"]}
          />
          <mesh
            name="Cube017_1"
            geometry={nodes.Cube017_1.geometry}
            material={materials["BrownDark.038"]}
          />
          <mesh
            name="Cube017_2"
            geometry={nodes.Cube017_2.geometry}
            material={materials["Stone.010"]}
          />
        </group>
        <mesh
          name="BackWingsContainer"
          geometry={nodes.BackWingsContainer.geometry}
          material={materials.HelicopterBody}
          position={[22.07, 6.357, -67.271]}
          rotation={[0, 0, -0.001]}
          scale={4.675}
        />
        <group
          name="HelicopterBody"
          position={[25.181, 8.663, -51.551]}
          rotation={[-0.166, 0.035, -0.028]}
          scale={6.833}
        >
          <mesh
            name="Sphere010"
            geometry={nodes.Sphere010.geometry}
            material={materials["HelicopterBody.001"]}
          />
          <mesh
            name="Sphere010_1"
            geometry={nodes.Sphere010_1.geometry}
            material={materials.Interior}
          />
        </group>
        <mesh
          name="TopFin"
          geometry={nodes.TopFin.geometry}
          material={materials.Metal}
          position={[25.825, 17.404, -51.08]}
          rotation={[2.993, -0.569, -3.109]}
          scale={6.833}
        />

        {/*Nave espacial */}

        <RigidBody
          type="kinematicPositionBased"
          colliders="trimesh"
          ref={spaceshipRef}
          mass={400}
          friction={1}
          restitution={0}
        >
          <group
            name="Cube003"
            position={[48.836, 66.157, -309.236]}
            scale={1.688}
          >
            <group ref={cameraTarget} position-z={7.5} />
            <group ref={cameraPosition} position-y={10} position-z={-60} />
            <mesh
              name="Cube005"
              geometry={nodes.Cube005.geometry}
              material={materials.Mat0}
            />
            <mesh
              name="Cube005_1"
              geometry={nodes.Cube005_1.geometry}
              material={materials.Mat1}
            />
            <mesh
              name="Cube005_2"
              geometry={nodes.Cube005_2.geometry}
              material={materials.Mat2}
            />
            <mesh
              name="Cube005_3"
              geometry={nodes.Cube005_3.geometry}
              material={materials.Window_Frame}
            />
            <mesh
              name="Cube005_4"
              geometry={nodes.Cube005_4.geometry}
              material={materials.Mat4}
            />
            <mesh
              name="Cube005_5"
              geometry={nodes.Cube005_5.geometry}
              material={materials.Mat3}
            />
            <mesh
              name="Cube005_6"
              geometry={nodes.Cube005_6.geometry}
              material={materials.Window}
            />
          </group>
        </RigidBody>
        <mesh
          name="chair"
          geometry={nodes.chair.geometry}
          material={materials["BrownDark.052"]}
          position={[-60.843, 7.315, -91.84]}
          rotation={[2.376, 1.425, -2.381]}
          scale={5.914}
        />
        <mesh
          name="boat_large_8angles003"
          geometry={nodes.boat_large_8angles003.geometry}
          material={materials.wood}
          position={[-34.067, 10.711, -136.285]}
          rotation={[-0.061, 0.206, 0.535]}
          scale={21.21}
        />
        <group
          name="lampPost002"
          position={[105.439, 9.299, -4.597]}
          scale={[12.31, 20.488, 20.488]}
        >
          <mesh
            name="Cylinder002"
            geometry={nodes.Cylinder002.geometry}
            material={materials["Black.012"]}
          />
          <mesh
            name="Cylinder002_1"
            geometry={nodes.Cylinder002_1.geometry}
            material={materials["Yellow.007"]}
          />
        </group>
        <group
          name="lampPost003"
          position={[-47.007, 3.555, -108.06]}
          scale={[8.612, 14.333, 14.333]}
        >
          <mesh
            name="Cylinder003"
            geometry={nodes.Cylinder003.geometry}
            material={materials["Black.012"]}
          />
          <mesh
            name="Cylinder003_1"
            geometry={nodes.Cylinder003_1.geometry}
            material={materials["Yellow.007"]}
          />
        </group>
        <group
          name="lampPost004"
          position={[61.338, 5.042, 3.293]}
          scale={[17.353, 28.881, 28.881]}
        >
          <mesh
            name="Cylinder004"
            geometry={nodes.Cylinder004.geometry}
            material={materials["Black.012"]}
          />
          <mesh
            name="Cylinder004_1"
            geometry={nodes.Cylinder004_1.geometry}
            material={materials["Yellow.007"]}
          />
        </group>
        <group
          name="lampPost005"
          position={[-34.446, -4.04, 4.929]}
          scale={[17.353, 28.881, 28.881]}
        >
          <mesh
            name="Cylinder005"
            geometry={nodes.Cylinder005.geometry}
            material={materials["Black.012"]}
          />
          <mesh
            name="Cylinder005_1"
            geometry={nodes.Cylinder005_1.geometry}
            material={materials["Yellow.007"]}
          />
        </group>
        <RigidBody
          type="fixed"
          colliders="trimesh"
          restitution={0.4}
          ref={fixedColliderRef}
        >
          <group
            name="axeDouble_uncommon001"
            position={[-47.477, 16.654, -150.649]}
            rotation={[0.536, 0.628, 0.691]}
            scale={18.759}
          >
            <mesh
              name="Cube002"
              geometry={nodes.Cube002.geometry}
              material={materials["Metal.074"]}
            />
            <mesh
              name="Cube002_1"
              geometry={nodes.Cube002_1.geometry}
              material={materials["BrownDark.039"]}
            />
            <mesh
              name="Cube002_2"
              geometry={nodes.Cube002_2.geometry}
              material={materials["Stone.012"]}
            />
          </group>
          <mesh
            name="formation_stone002"
            geometry={nodes.formation_stone002.geometry}
            material={materials["stone.001"]}
            position={[76.161, -2.682, -77.854]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={43.067}
          />
          <mesh
            name="formation_stone003"
            geometry={nodes.formation_stone003.geometry}
            material={materials["stone.001"]}
            position={[-67.011, -2.12, -156.462]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={34.823}
          />
          <mesh
            name="formation_stone004"
            geometry={nodes.formation_stone004.geometry}
            material={materials["stone.001"]}
            position={[69.541, -6.471, -165.385]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={32.462}
          />
          <group
            name="lampPost001"
            position={[-78.256, 9.299, -3.51]}
            scale={[12.31, 20.488, 20.488]}
          >
            <mesh
              name="Cylinder006"
              geometry={nodes.Cylinder006.geometry}
              material={materials["Black.012"]}
            />
            <mesh
              name="Cylinder006_1"
              geometry={nodes.Cylinder006_1.geometry}
              material={materials["Yellow.007"]}
            />
          </group>
          <group name="car" position={[0.043, 1.271, 178.19]} scale={0.134}>
            <mesh
              name="Cylinder018_Cylinder007"
              geometry={nodes.Cylinder018_Cylinder007.geometry}
              material={materials.Car}
            />
            <mesh
              name="Cylinder018_Cylinder007_1"
              geometry={nodes.Cylinder018_Cylinder007_1.geometry}
              material={materials.Windshield}
            />
            <mesh
              name="Cylinder018_Cylinder007_2"
              geometry={nodes.Cylinder018_Cylinder007_2.geometry}
              material={materials["Material.023"]}
            />
            <mesh
              name="Cylinder018_Cylinder007_3"
              geometry={nodes.Cylinder018_Cylinder007_3.geometry}
              material={materials["Material.024"]}
            />
          </group>
          <group
            name="car001"
            position={[-94.026, 7.452, 341.554]}
            rotation={[-0.603, 0.644, 0]}
            scale={0.666}
          >
            <mesh
              name="Cylinder018_Cylinder001"
              geometry={nodes.Cylinder018_Cylinder001.geometry}
              material={materials.Car}
            />
            <mesh
              name="Cylinder018_Cylinder001_1"
              geometry={nodes.Cylinder018_Cylinder001_1.geometry}
              material={materials.Windshield}
            />
          </group>
          <mesh
            name="rocksA_desert"
            geometry={nodes.rocksA_desert.geometry}
            material={materials["BrownDark.013"]}
            position={[90.252, 0.288, 259.068]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={16.732}
          />
          <group
            name="ship_wreck_8angles"
            position={[-69.134, 13.978, 310.825]}
            rotation={[0.289, 0.064, 0.837]}
            scale={5.538}
          >
            <mesh
              name="ship_wreck_8angles_1"
              geometry={nodes.ship_wreck_8angles_1.geometry}
              material={materials["wood.020"]}
            />
            <mesh
              name="ship_wreck_8angles_2"
              geometry={nodes.ship_wreck_8angles_2.geometry}
              material={materials["iron.010"]}
            />
            <mesh
              name="ship_wreck_8angles_3"
              geometry={nodes.ship_wreck_8angles_3.geometry}
              material={materials["woodDark.002"]}
            />
            <mesh
              name="ship_wreck_8angles_4"
              geometry={nodes.ship_wreck_8angles_4.geometry}
              material={materials["window.002"]}
            />
            <mesh
              name="ship_wreck_8angles_5"
              geometry={nodes.ship_wreck_8angles_5.geometry}
              material={materials["leaves.006"]}
            />
            <mesh
              name="ship_wreck_8angles_6"
              geometry={nodes.ship_wreck_8angles_6.geometry}
              material={materials["_defaultMat.004"]}
            />
          </group>
          <group
            name="tower"
            position={[96.565, 0.17, 163.62]}
            rotation={[-Math.PI, 1.036, -Math.PI]}
            scale={8.2}
          >
            <mesh
              name="tower_1"
              geometry={nodes.tower_1.geometry}
              material={materials["stone.006"]}
            />
            <mesh
              name="tower_2"
              geometry={nodes.tower_2.geometry}
              material={materials["woodDark.003"]}
            />
            <mesh
              name="tower_3"
              geometry={nodes.tower_3.geometry}
              material={materials["_defaultMat.007"]}
            />
            <mesh
              name="tower_4"
              geometry={nodes.tower_4.geometry}
              material={materials["iron.011"]}
            />
            <mesh
              name="tower_5"
              geometry={nodes.tower_5.geometry}
              material={materials["wood.024"]}
            />
            <mesh
              name="tower_6"
              geometry={nodes.tower_6.geometry}
              material={materials["sand.006"]}
            />
            <mesh
              name="tower_7"
              geometry={nodes.tower_7.geometry}
              material={materials["textile.008"]}
            />
          </group>
          <group
            name="character_witch001"
            position={[69.843, 30.256, 333.156]}
            rotation={[Math.PI / 2, 0, 3.08]}
            scale={6.735}
          >
            <mesh
              name="Cube020"
              geometry={nodes.Cube020.geometry}
              material={materials["Purple.008"]}
            />
            <mesh
              name="Cube020_1"
              geometry={nodes.Cube020_1.geometry}
              material={materials["Black.019"]}
            />
            <mesh
              name="Cube020_2"
              geometry={nodes.Cube020_2.geometry}
              material={materials["Yellow.010"]}
            />
            <mesh
              name="Cube020_3"
              geometry={nodes.Cube020_3.geometry}
              material={materials["GreenLight.003"]}
            />
            <group name="character_witchArmLeft" position={[0.204, 0, -0.634]}>
              <mesh
                name="Cube018"
                geometry={nodes.Cube018.geometry}
                material={materials["GreenLight.003"]}
              />
              <mesh
                name="Cube018_1"
                geometry={nodes.Cube018_1.geometry}
                material={materials["Purple.008"]}
              />
            </group>
            <group
              name="character_witchArmRight"
              position={[-0.204, 0, -0.634]}
            >
              <mesh
                name="Cube019"
                geometry={nodes.Cube019.geometry}
                material={materials["Purple.008"]}
              />
              <mesh
                name="Cube019_1"
                geometry={nodes.Cube019_1.geometry}
                material={materials["GreenLight.003"]}
              />
            </group>
            <group name="character_witchHead" position={[0, 0, -0.704]}>
              <mesh
                name="Cube001"
                geometry={nodes.Cube001.geometry}
                material={materials["Black.019"]}
              />
              <mesh
                name="Cube001_1"
                geometry={nodes.Cube001_1.geometry}
                material={materials["GreenLight.003"]}
              />
              <mesh
                name="Cube001_2"
                geometry={nodes.Cube001_2.geometry}
                material={materials["Green.003"]}
              />
              <group
                name="character_witchHat"
                position={[0, -0.071, -0.768]}
                rotation={[-0.264, 0, 0]}
              >
                <mesh
                  name="Cube016"
                  geometry={nodes.Cube016.geometry}
                  material={materials["Purple.008"]}
                />
                <mesh
                  name="Cube016_1"
                  geometry={nodes.Cube016_1.geometry}
                  material={materials["Black.019"]}
                />
                <mesh
                  name="Cube016_2"
                  geometry={nodes.Cube016_2.geometry}
                  material={materials["Yellow.010"]}
                />
              </group>
            </group>
          </group>
          <mesh
            name="treeD_graveyard"
            geometry={nodes.treeD_graveyard.geometry}
            material={materials["DarkWood.015"]}
            position={[-42.578, 0.387, 197.439]}
            scale={6.693}
          />
          <group
            name="tower001"
            position={[-96.645, 0.17, 250.19]}
            rotation={[0, -1.227, 0]}
            scale={8.2}
          >
            <mesh
              name="tower001_1"
              geometry={nodes.tower001_1.geometry}
              material={materials["stone.006"]}
            />
            <mesh
              name="tower001_2"
              geometry={nodes.tower001_2.geometry}
              material={materials["woodDark.003"]}
            />
            <mesh
              name="tower001_3"
              geometry={nodes.tower001_3.geometry}
              material={materials["_defaultMat.007"]}
            />
            <mesh
              name="tower001_4"
              geometry={nodes.tower001_4.geometry}
              material={materials["iron.011"]}
            />
            <mesh
              name="tower001_5"
              geometry={nodes.tower001_5.geometry}
              material={materials["wood.024"]}
            />
            <mesh
              name="tower001_6"
              geometry={nodes.tower001_6.geometry}
              material={materials["sand.006"]}
            />
            <mesh
              name="tower001_7"
              geometry={nodes.tower001_7.geometry}
              material={materials["textile.008"]}
            />
          </group>
          <mesh
            name="rocksA_desert001"
            geometry={nodes.rocksA_desert001.geometry}
            material={materials["BrownDark.013"]}
            position={[90.252, 0.288, 259.068]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={16.732}
          />
          <mesh
            name="rocksA_desert002"
            geometry={nodes.rocksA_desert002.geometry}
            material={materials["BrownDark.013"]}
            position={[-34.855, 0.288, 165.588]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={16.732}
          />
          <mesh
            name="treeD_graveyard001"
            geometry={nodes.treeD_graveyard001.geometry}
            material={materials["DarkWood.015"]}
            position={[68.55, 0.387, 151.835]}
            scale={6.693}
          />
          <mesh
            name="treeD_graveyard002"
            geometry={nodes.treeD_graveyard002.geometry}
            material={materials["DarkWood.015"]}
            position={[-103.909, 0.387, 266.807]}
            scale={6.693}
          />
          <mesh
            name="treeD_graveyard003"
            geometry={nodes.treeD_graveyard003.geometry}
            material={materials["DarkWood.015"]}
            position={[7.428, 0.387, 282.003]}
            scale={6.693}
          />
          <mesh
            name="treeD_graveyard004"
            geometry={nodes.treeD_graveyard004.geometry}
            material={materials["DarkWood.015"]}
            position={[89.014, 0.387, 326.752]}
            scale={6.693}
          />
          <mesh
            name="Landscape004"
            geometry={nodes.Landscape004.geometry}
            material={materials["Material.028"]}
            position={[56.796, 0.499, 198.109]}
            scale={57.011}
          />
          <mesh
            name="Landscape006"
            geometry={nodes.Landscape006.geometry}
            material={materials["Material.027"]}
            position={[-56.585, 0.545, 198.042]}
            scale={56.917}
          />
          <mesh
            name="Landscape005"
            geometry={nodes.Landscape005.geometry}
            material={materials.Material}
            position={[56.833, 0.545, 310.933]}
            rotation={[Math.PI, -0.004, Math.PI]}
            scale={56.917}
          />
          <group
            name="Landscape007"
            position={[-56.396, 0.499, 311.227]}
            rotation={[-Math.PI, 0.001, -Math.PI]}
            scale={57.011}
          >
            <mesh
              name="Landscape008"
              geometry={nodes.Landscape008.geometry}
              material={materials["Material.026"]}
            />
            <mesh
              name="Landscape008_1"
              geometry={nodes.Landscape008_1.geometry}
              material={materials["Material.029"]}
            />
          </group>
          <mesh
            name="Landscape001"
            geometry={nodes.Landscape001.geometry}
            material={materials["Material.001"]}
            position={[-37.738, 0, -43.105]}
            scale={[52.174, 90.12, 49.433]}
          />
          <mesh
            name="Landscape002"
            geometry={nodes.Landscape002.geometry}
            material={materials["Material.003"]}
            position={[2.785, -0.364, 74.994]}
            rotation={[3.14, 0, 0]}
            scale={-68.725}
          />
          <mesh
            name="Landscape003"
            geometry={nodes.Landscape003.geometry}
            material={materials["Material.004"]}
            position={[38.7, -2.216, -258.957]}
            rotation={[3.14, 0, 0]}
            scale={-68.922}
          />
        </RigidBody>
      </group>
    </group>
  );
}

useGLTF.preload("./models/MixedScenarios.glb");
