/* eslint-disable no-unused-vars */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/models/SpaceshipScene.glb 
*/

import React, { useEffect, useRef, useState } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useControls } from "./UseControls";
import { SkeletonUtils } from "three-stdlib";
import * as THREE from "three";
import { useFrame, useThree } from "@react-three/fiber";
import { RigidBody } from "@react-three/rapier";

export function SpaceshipScene(props) {
  const group = React.useRef();
  //  const { scene } = useGLTF("./models/SpaceshipScene.glb");
  //  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials, animations } = useGLTF(
    "./models/SpaceshipScene.glb"
  );
  const { actions } = useAnimations(animations, group);

  const controls = useControls();
  const spaceshipRef = useRef();
  const cameraTarget = useRef();
  const cameraPosition = useRef();
  const cameraWorldPosition = useRef(new THREE.Vector3());
  const cameraLookAtWorldPosition = useRef(new THREE.Vector3());
  const cameraLookAt = useRef(new THREE.Vector3());
  const [initialPosition] = useState(new THREE.Vector3(-0.163, 0.566, -0.056));
  const [initialRotation] = useState(
    new THREE.Quaternion().setFromEuler(new THREE.Euler(0, 0, 0))
  );

  useFrame(({ camera }) => {
    //    cameraPosition.current.getWorldPosition(cameraWorldPosition.current);
    //    camera.position.lerp(cameraWorldPosition.current, 0.1);
    //
    //    if (cameraTarget.current) {
    //      cameraTarget.current.getWorldPosition(cameraLookAtWorldPosition.current);
    //      cameraLookAt.current.lerp(cameraLookAtWorldPosition.current, 0.1);
    //
    //      camera.lookAt(cameraLookAt.current);
    //    }

    const spaceship = spaceshipRef.current;

    if (!spaceship) return;

    const impulse = 2;
    const torque = 0.3;
    const maxSpeed = 10; // Velocidad máxima
    const velocity = spaceship.linvel();
    const speed = Math.sqrt(
      velocity.x ** 2 + velocity.y ** 2 + velocity.z ** 2
    );

    if (speed > maxSpeed) {
      const scale = maxSpeed / speed;
      spaceship.setLinvel(
        { x: velocity.x * scale, y: velocity.y * scale, z: velocity.z * scale },
        true
      );
    }

    const forwardVector = new THREE.Vector3(0, 0, 4).applyQuaternion(
      spaceship.rotation()
    );

    if (controls.forward) {
      spaceship.applyImpulse(forwardVector.multiplyScalar(impulse));
    }
    if (controls.back) {
      spaceship.applyImpulse(forwardVector.multiplyScalar(-impulse));
    }
    if (controls.left) {
      spaceship.applyTorqueImpulse({ x: 0, y: torque, z: 0 });
    }
    if (controls.right) {
      spaceship.applyTorqueImpulse({ x: 0, y: -torque, z: 0 });
    }
    if (controls.jump) {
      spaceship.applyImpulse({ x: 0, y: 3, z: 0 });
    }
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="Armature_druide"
          position={[6.361, 1.431, 11.024]}
          rotation={[Math.PI, -0.978, Math.PI]}
          scale={14.742}
        >
          <primitive object={nodes.root} />
          <group name="druid">
            <skinnedMesh
              name="druid001"
              geometry={nodes.druid001.geometry}
              material={materials.color_main}
              skeleton={nodes.druid001.skeleton}
            />
            <skinnedMesh
              name="druid001_1"
              geometry={nodes.druid001_1.geometry}
              material={materials["Material.006"]}
              skeleton={nodes.druid001_1.skeleton}
            />
            <skinnedMesh
              name="druid001_2"
              geometry={nodes.druid001_2.geometry}
              material={materials["Material.007"]}
              skeleton={nodes.druid001_2.skeleton}
            />
          </group>
        </group>
        <mesh
          name="boat_large_8angles"
          geometry={nodes.boat_large_8angles.geometry}
          material={materials.wood}
          position={[12.166, 2.299, -17.75]}
          rotation={[0.508, -0.575, 0.554]}
          scale={4.075}
        />
        <group
          name="cannonLarge"
          position={[-12.288, 0.347, 0.145]}
          rotation={[0.019, -0.367, 0.048]}
          scale={5.658}
        >
          <mesh
            name="cannonLarge_1"
            geometry={nodes.cannonLarge_1.geometry}
            material={materials["wood.005"]}
          />
          <mesh
            name="cannonLarge_2"
            geometry={nodes.cannonLarge_2.geometry}
            material={materials["iron.002"]}
          />
          <mesh
            name="barrel_1"
            geometry={nodes.barrel_1.geometry}
            material={materials["iron.002"]}
            position={[0, 0.348, -0.067]}
            rotation={[0.395, 0.067, -0.785]}
          />
        </group>
        <mesh
          name="Barn_001"
          geometry={nodes.Barn_001.geometry}
          material={materials.None}
          position={[-14.341, 1.235, -9.828]}
          rotation={[-Math.PI, 1.381, -Math.PI]}
          scale={2.144}
        />
        <group
          name="axeDouble_uncommon"
          position={[18.837, 0.952, -16.802]}
          rotation={[0.872, 0.477, -2.725]}
          scale={2.182}
        >
          <mesh
            name="Cube014"
            geometry={nodes.Cube014.geometry}
            material={materials["Metal.074"]}
          />
          <mesh
            name="Cube014_1"
            geometry={nodes.Cube014_1.geometry}
            material={materials["BrownDark.039"]}
          />
          <mesh
            name="Cube014_2"
            geometry={nodes.Cube014_2.geometry}
            material={materials["Stone.012"]}
          />
        </group>
        <group
          name="axe_uncommon"
          position={[24.154, 8.232, -0.325]}
          rotation={[-0.645, 1.062, 1.644]}
          scale={4.365}
        >
          <mesh
            name="Cube017"
            geometry={nodes.Cube017.geometry}
            material={materials["Metal.072"]}
          />
          <mesh
            name="Cube017_1"
            geometry={nodes.Cube017_1.geometry}
            material={materials["BrownDark.038"]}
          />
          <mesh
            name="Cube017_2"
            geometry={nodes.Cube017_2.geometry}
            material={materials["Stone.010"]}
          />
        </group>
        <mesh
          name="BackWingsContainer"
          geometry={nodes.BackWingsContainer.geometry}
          material={materials.HelicopterBody}
          position={[5.679, 1.349, -4.956]}
          rotation={[0, 0, -0.001]}
        />
        <mesh
          name="GatlingGun"
          geometry={nodes.GatlingGun.geometry}
          material={materials.Metal}
          position={[-17122.896, 15.118, 3010.017]}
          rotation={[0, 0, -0.001]}
        />
        <group
          name="HelicopterBody"
          position={[6.426, 2.179, -1.972]}
          rotation={[-0.09, 0.182, -0.269]}
          scale={1.462}
        >
          <mesh
            name="Sphere010"
            geometry={nodes.Sphere010.geometry}
            material={materials["HelicopterBody.001"]}
          />
          <mesh
            name="Sphere010_1"
            geometry={nodes.Sphere010_1.geometry}
            material={materials.Interior}
          />
        </group>
        <group
          name="Sphere"
          position={[6.308, 1.286, -1.379]}
          rotation={[0, 0, -0.001]}
        >
          <mesh
            name="Sphere007"
            geometry={nodes.Sphere007.geometry}
            material={materials.Windsheild}
          />
          <mesh
            name="Sphere007_1"
            geometry={nodes.Sphere007_1.geometry}
            material={materials.WindSheildDark}
          />
        </group>
        <mesh
          name="StandPlane"
          geometry={nodes.StandPlane.geometry}
          material={materials.Stand}
          position={[-2177.924, 2.407, 382.553]}
          rotation={[0, 0, -0.001]}
        />
        <mesh
          name="TopFin"
          geometry={nodes.TopFin.geometry}
          material={materials.Metal}
          position={[7.048, 3.945, -1.825]}
          rotation={[-3.055, -0.693, -2.795]}
          scale={1.462}
        />
        <group name="lampPost" position={[-12.315, 0.615, -9.243]}>
          <mesh
            name="Cylinder096"
            geometry={nodes.Cylinder096.geometry}
            material={materials["Black.012"]}
          />
          <mesh
            name="Cylinder096_1"
            geometry={nodes.Cylinder096_1.geometry}
            material={materials["Yellow.007"]}
          />
        </group>
        <mesh
          name="formation_stone"
          geometry={nodes.formation_stone.geometry}
          material={materials["stone.001"]}
          position={[-7.933, 0.913, -6.583]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={2.162}
        />
        <RigidBody
          type="kinematicPositionBased"
          colliders="hull"
          ref={spaceshipRef}
          mass={100}
          friction={0.2}
          restitution={0.3}
        >
          <group name="Cube003" position={[16.587, 9.287, -54.439]}>
            <mesh
              name="Cube005"
              geometry={nodes.Cube005.geometry}
              material={materials.Mat0}
            />
            <mesh
              name="Cube005_1"
              geometry={nodes.Cube005_1.geometry}
              material={materials.Mat1}
            />
            <mesh
              name="Cube005_2"
              geometry={nodes.Cube005_2.geometry}
              material={materials.Mat2}
            />
            <mesh
              name="Cube005_3"
              geometry={nodes.Cube005_3.geometry}
              material={materials.Window_Frame}
            />
            <mesh
              name="Cube005_4"
              geometry={nodes.Cube005_4.geometry}
              material={materials.Mat4}
            />
            <mesh
              name="Cube005_5"
              geometry={nodes.Cube005_5.geometry}
              material={materials.Mat3}
            />
            <mesh
              name="Cube005_6"
              geometry={nodes.Cube005_6.geometry}
              material={materials.Window}
            />
          </group>
        </RigidBody>
        <mesh
          name="chair"
          geometry={nodes.chair.geometry}
          material={materials["BrownDark.052"]}
          position={[-13.701, 1.529, -10.058]}
          rotation={[2.376, 1.425, -2.381]}
          scale={0.83}
        />
        <mesh
          name="boat_large_8angles001"
          geometry={nodes.boat_large_8angles001.geometry}
          material={materials.wood}
          position={[15.008, 0.256, -6.117]}
          rotation={[0.136, 0, 0]}
          scale={1.813}
        />
        <mesh
          name="boat_large_8angles002"
          geometry={nodes.boat_large_8angles002.geometry}
          material={materials.wood}
          position={[-1.646, 1.276, -4.124]}
          rotation={[0.296, -0.054, 2.911]}
          scale={1.813}
        />
        <mesh
          name="boat_large_8angles003"
          geometry={nodes.boat_large_8angles003.geometry}
          material={materials.wood}
          position={[-7.099, 1.06, -22.726]}
          rotation={[-0.061, 0.206, 0.535]}
          scale={4.082}
        />
        <group name="lampPost001" position={[-13.651, 2.888, -12.045]}>
          <mesh
            name="Cylinder001"
            geometry={nodes.Cylinder001.geometry}
            material={materials["Black.012"]}
          />
          <mesh
            name="Cylinder001_1"
            geometry={nodes.Cylinder001_1.geometry}
            material={materials["Yellow.007"]}
          />
        </group>
        <group
          name="lampPost002"
          position={[24.28, 1.175, 8.771]}
          scale={[2.633, 4.383, 4.383]}
        >
          <mesh
            name="Cylinder002"
            geometry={nodes.Cylinder002.geometry}
            material={materials["Black.012"]}
          />
          <mesh
            name="Cylinder002_1"
            geometry={nodes.Cylinder002_1.geometry}
            material={materials["Yellow.007"]}
          />
        </group>
        <group
          name="lampPost003"
          position={[15.509, 0.578, 1.761]}
          scale={[2.748, 4.573, 4.573]}
        >
          <mesh
            name="Cylinder003"
            geometry={nodes.Cylinder003.geometry}
            material={materials["Black.012"]}
          />
          <mesh
            name="Cylinder003_1"
            geometry={nodes.Cylinder003_1.geometry}
            material={materials["Yellow.007"]}
          />
        </group>
        <group
          name="lampPost004"
          position={[14.003, 0.665, 10.766]}
          scale={[3.712, 6.178, 6.178]}
        >
          <mesh
            name="Cylinder004"
            geometry={nodes.Cylinder004.geometry}
            material={materials["Black.012"]}
          />
          <mesh
            name="Cylinder004_1"
            geometry={nodes.Cylinder004_1.geometry}
            material={materials["Yellow.007"]}
          />
        </group>
        <group
          name="lampPost005"
          position={[-5.82, 0.379, 10.617]}
          scale={[3.712, 6.178, 6.178]}
        >
          <mesh
            name="Cylinder005"
            geometry={nodes.Cylinder005.geometry}
            material={materials["Black.012"]}
          />
          <mesh
            name="Cylinder005_1"
            geometry={nodes.Cylinder005_1.geometry}
            material={materials["Yellow.007"]}
          />
        </group>
        <RigidBody type="fixed" colliders="trimesh" restitution={0.4}>
          <group
            name="axeDouble_uncommon001"
            position={[-8.608, 4.806, -22.664]}
            rotation={[0.536, 0.628, 0.691]}
            scale={4.013}
          >
            <mesh
              name="Cube002"
              geometry={nodes.Cube002.geometry}
              material={materials["Metal.074"]}
            />
            <mesh
              name="Cube002_1"
              geometry={nodes.Cube002_1.geometry}
              material={materials["BrownDark.039"]}
            />
            <mesh
              name="Cube002_2"
              geometry={nodes.Cube002_2.geometry}
              material={materials["Stone.012"]}
            />
          </group>

          <mesh
            name="formation_stone001"
            geometry={nodes.formation_stone001.geometry}
            material={materials["stone.001"]}
            position={[-7.775, 0.669, 3.724]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={2.162}
          />
          <mesh
            name="formation_stone002"
            geometry={nodes.formation_stone002.geometry}
            material={materials["stone.001"]}
            position={[17.841, 0.669, -7.092]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={9.213}
          />
          <mesh
            name="formation_stone003"
            geometry={nodes.formation_stone003.geometry}
            material={materials["stone.001"]}
            position={[-12.659, -0.111, -24.556]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={8.803}
          />
          <mesh
            name="formation_stone004"
            geometry={nodes.formation_stone004.geometry}
            material={materials["stone.001"]}
            position={[16.425, -0.141, -25.816]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={6.944}
          />
          <mesh
            name="Landscape001"
            geometry={nodes.Landscape001.geometry}
            material={materials["Material.001"]}
            position={[-7.235, 0, 0.321]}
            scale={[11.498, 19.861, 10.894]}
          />
          <mesh
            name="Landscape002"
            geometry={nodes.Landscape002.geometry}
            material={materials["Material.003"]}
            position={[3.3, -0.005, 20.898]}
            rotation={[3.14, 0, 0]}
            scale={-9.831}
          />
          <mesh
            name="Landscape003"
            geometry={nodes.Landscape003.geometry}
            material={materials["Material.004"]}
            position={[15.59, -0.291, -41.953]}
            rotation={[3.14, 0, 0]}
            scale={-9.831}
          />
        </RigidBody>
      </group>
    </group>
  );
}

useGLTF.preload("./models/SpaceshipScene.glb");
